# -*- coding: utf-8 -*-
"""Qard_Case_Study_test_NER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_UDuZKj-V33-p_VMN6nlxthTNgUEkQ-8

# Description
This notebook explores the performance of different NER methods

These methods includes Spacy and camembert-ner

The difference on languages are also considered(EN and FR)

The conclusion is: **camembert-ner > Spacy-EN > Spacy-FR**

### Install Dependencies
"""

! apt-get install poppler-utils
! apt-get install tesseract-ocr

! pip install pdf2image
! pip install pytesseract
! pip install pip setuptools wheel
! pip install spacy
! pip install googletrans
! pip install transformers
! pip install sentencepiece

! python -m spacy download en_core_web_sm
! python -m spacy download fr_core_news_sm

"""### Upload the pdf"""

from google.colab import files
uploaded = files.upload()

! mkdir pdf
! mv test1.pdf pdf/test1.pdf
! mkdir img

"""### PDF2image
images are saved as ppm format
A PPM file is a 24-bit color image formatted using a text format. It stores each pixel with a number from 0 to 65536, which specifies the color of the pixel. PPM files also store the image height and width, whitespace data, and the maximum color value.

"""

from pdf2image import convert_from_path, convert_from_bytes

images_from_path = convert_from_path('pdf/test1.pdf', output_folder='img/')

"""### OCR pytesseract"""

import pytesseract
from PIL import Image

! ls img/

text = pytesseract.image_to_string(Image.open('img/886d9d4a-daea-4571-9e3f-e035361ab0b0-02.ppm'))
print(text)

"""### Spacy NER

the in-built MER French model of Spacy is very inaccurate and limited, for example it can tell Apple from **Apple est une entreprise internationale** but can't tell Tesla from **Tesla est une entreprise international**. when seeing an unseen company name, it would most likely fail.
"""

import spacy
from spacy import displacy
import fr_core_news_sm
# import en_core_web_sm

def show_ents(doc):
  if doc.ents:
    for ent in doc.ents:
      print('|'.join([ent.text.strip(), ent.label_, str(spacy.explain(ent.label_))]))

text1 = 'Apple est une entreprise internationale'
text2 = 'Tesla est une entreprise internationale'
text3 =  'TUR - MAN est une entreprise internationale'
text4 = 'La dénomination de la société est : TUR - MAN'
nlp = fr_core_news_sm.load()
for t in [text1, text2, text3, text4]:
  doc = nlp(t)
  show_ents(doc)
  # displacy.render(doc, style='ent',jupyter=True, options={'ents': ['ORG', 'PRODUCT']})
  # displacy.render(doc, style='ent',jupyter=True)

"""Let's try the English NER model"""

import en_core_web_sm
text1 = 'Apple is an international company'
text2 = 'Tesla is an international company'
text3 = 'TUR - MAN is an international company'
text4 = 'NAME The name of the company is: TUR - MAN'
nlp = en_core_web_sm.load()
for t in [text1, text2, text3, text4]:
  doc = nlp(t)
  show_ents(doc)
  # displacy.render(doc, style='ent',jupyter=True)

"""I translated the page into English using GoogleTranslate, the NER is still a big mess, to many False Positives"""

text_translated = """
Each share gives its owner an equal right in your shareholder's profits and in all assets.
social. Any share gives the right to a vote in all votes and deliberations.

 

Any transfer of shares must be recorded by a notarial deed or under private signature to be enforceable 8 days
company, it must be served by bailiff's writ or be accepted by it in a notarial deed.

The shares are freely transferable between partners. They cannot be sold to foreign third parties.
company, only with the consent of the majority of associates representing at least three / quarters of the shares
social, this majority being determined taking into account the person and the shares of the cbdant lassoé. the
consent is requested in accordance with the procedure provided for by law. The shares are freely transferable
by vale of succession or in the event of community liquidation between spouses, and freely transferable between
spouses and between ascendants.

acquisition by the spouse, subsequent to the realization of the ownership or the purchase, as a partner
under the conditions set by fartlele 1832-2 of the Civil Code, is subject to the consent of the Maforité des
associated, representing at least bes three / quarters of the soda shares.

The company has given its consent to a plan to pledge shares, either by notification of
its decision & the interested party, either by default of response within a period of three months & from the request, this
consent will result in the consent of the assignee in the event of formalization of shares, according to the
provisions of Article 207, paragraphs 1 ° of the Civil Code, 3 unless the company prefers, after transfer, to redeem
without dei the living shares reduce the capital.

Article 31 ~ RESPONSIBILITY OF PARTNERS
Assotids are only liable to third parties up to the amount of their contribution.

they are, however, voluntarily respansabies for five years, vis-a-vis the thirds, of the value attributed to
spposts in natare.

This responsibility only comes into play if there has been no intervention by a commissioner in an apartment or
when [the value retained by your partner is different from that proposed by the contribution auditor.

In addition, you are reminded that, in accordance with your law, forsque reorganization or judicial liquidation
an Insufficiency of assets, the court may, in the event of a mismanagement that contributed to this
insufficient, decide that the debts of the company will be borne in whole or in part, by the directors of
law or de facto, or some of them, with or without sofidarity.

Article 32 ~ MANAGEMENT
Modatted:

The sockété is managed by one or more natural persons, associates or not, appointed with or without.
time limit. In the latter case, the geranite (s) are always eligible.

The managers are appointed by deviation from partners representing more than half of the shares.

In compensation for his duties, each manager is entitled to a fixed, proportional or mixed salary, the amount of which
amount and modalities of palerment health determined by collective ardinary decision of the partners.
"""
doc = nlp(text_translated)
show_ents(doc)
# displacy.render(doc, style='ent',jupyter=True)

"""***Another problem of translating the document into English before using Spacy NER, is that it can't be scaled as translation APIs are costly. ***

### **camembert-ner NER**
[camembert-ner] is a NER model that was fine-tuned from camemBERT on wikiner-fr dataset. Model was trained on wikiner-fr dataset (~170 634 sentences). Model was validated on emails/chat data and overperformed other models on this type of data specifically. In particular the model seems to work better on entity that don't start with an upper case.
"""

from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline

tokenizer = AutoTokenizer.from_pretrained("Jean-Baptiste/camembert-ner")
model = AutoModelForTokenClassification.from_pretrained("Jean-Baptiste/camembert-ner")

nlp_tf = pipeline('ner', model=model, tokenizer=tokenizer, aggregation_strategy="simple")

"""the performance seems better"""

text1 = 'Apple est une entreprise internationale'
text2 = 'Tesla est une entreprise internationale'
text3 =  'TUR - MAN est une entreprise internationale'
text4 = 'La dénomination de la société est : TUR - MAN'

for item in nlp_tf(text.replace(' - ', '-')):
  # if item['entity_group']=='ORG':
    print(item)





